### ISSUE TITLE
Location for prelude.sh

### ISSUE THREAD

**Issue by m-kru** [alexherbo2/prelude.kak#1]
Should prelude.sh be placed inside autoload directory? I wanted to try auto-pairs plugin. I have copied `auto-pairs.kak`, `prelude.kak` and `prelude.sh` to the `~/.config/kak/autoload`. Now when I open kak it looks like my `kakrc` and `filetype.kak` are not loaded. There are no errors in the debug buffer.

**Comment by alexherbo2** [comment]
It is a quirk from Kakoune.  When you provide your own autoload, the default configuration is not loaded.

``` sh
ln -s /path/to/kakoune/rc ~/.config/kak/autoload/base
```

See the [5. Configuration & Autoloading] section for more details.

[5. Configuration & Autoloading]: https://github.com/mawww/kakoune#5-configuration--autoloading

**Comment by m-kru** [comment]
I have added symbolic link to my `kakrc`. However, now I get some error at the start
```
/home/user/.config/kak/kakrc:1:1: 'add-highlighter' duplicate id: 'number-lines_-hlcursor'
/home/user/workspace/kakoune/share/kak/kakrc:29:1: 'evaluate-commands' 5:1: 'source' 1:1: 'add-highlighter' duplicate id: 'number-lines_-hlcursor'
error while parsing kakrc:
    1:1: 'source' 29:1: 'evaluate-commands' 5:1: 'source' 1:1: 'add-highlighter' duplicate id: 'number-lines_-hlcursor'
```
It is weird, as this error does not appear when there is no `autoload` directory in `~/.config/kak`.  What is more, when I grep `/home/user/workspace/kakoune/share/kak/kakrc` there is no `add-highlighter` or `number-lines_-hlcursor`. There is one in my `kakrc`
```
add-highlighter global/ number-lines -hlcursor
```

**Comment by krobelus** [comment]
Sounds like you are sourcing your `kakrc` twice :thinking:. Is something in your `autoload` a symlink to `~/.config/kak/kakrc`, or a parent directory?

**Comment by m-kru** [comment]
![image](https://user-images.githubusercontent.com/26227737/93661068-2483c100-fa55-11ea-8694-28259b296c20.png)

**Comment by krobelus** [comment]
Yeah, you don't need the `base.kak -> ../kakrc`, kakrc is always loaded after all autoloads.

**Comment by m-kru** [comment]
@krobelus but then I have the issues described in the first message. No syntax highlight, no custom commands defined in kakrc, like `kakrc` and `filetype.kak` were not loaded. In such case I do not understand @alexherbo2 comment about symbolic linking.

**Comment by krobelus** [comment]
Oh yeah I see from the `tree` output that you didn't load the kak scripts that ship with the Kakoune installation

As mentioned in https://github.com/alexherbo2/prelude.kak/issues/1#issuecomment-695016942 you want something like

```
ln -s /usr/share/kak/rc/ ~/.config/kak/autoload/base
```

The point of this is that you can choose to only load a selection of kak scripts. A custom autoload directory replaces the default one, it does not extend it unless you link to it.

From `share/kak/kakrc`:

```sh
    if [ -d "${kak_config}/autoload" ]; then
        autoload_directory ${kak_config}/autoload
    elif [ -d "${kak_runtime}/autoload" ]; then
        autoload_directory ${kak_runtime}/autoload
    fi
```

**Comment by m-kru** [comment]
@krobelus thanks!

**Comment by alexherbo2** [comment]
@m-kru You can put or link the plugin repositories in your autoload.

**Comment by m-kru** [comment]
@alexherbo2 Do you mean that I can just clone into `~/.config/kak/autoload`?

**Comment by alexherbo2** [comment]
Yep, you can clone or symlink.
